### ISSUE TITLE
unable to resolve class okhttp3.OkHttpClient  

### ISSUE THREAD

**Issue by CMingTseng** [longforus/pgyerUpload4AndroidStudio#1]
Dear Sir 

as  you say 

{

import okhttp3.OkHttpClient//2.导入

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.squareup.okhttp3:okhttp:3.11.0'//1.添加依赖
    }
}

OkHttpClient client = new OkHttpClient()//3.可以用了

}

or 

Ref :  https://blog.csdn.net/angcyo/article/details/88692186

i get unable to resolve class okhttp3.OkHttpClient 

THX

**Comment by longforus** [comment]
@CMingTseng 
you must separate the 3 setp.
1.add classpath,sync project.
2.import and use

![TIM截图20200921111810](https://user-images.githubusercontent.com/18444240/93730662-30f64e00-fbfc-11ea-840d-58103019efb7.png)

**Comment by CMingTseng** [comment]
> @CMingTseng
> you must separate the 3 setp.
> 1.add classpath,sync project.
> 2.import and use
> 
> ![TIM截图20200921111810](https://user-images.githubusercontent.com/18444240/93730662-30f64e00-fbfc-11ea-840d-58103019efb7.png)


Dear Sir 

can add wechat ?


 my step  (first time  get error !!)

1.   add 

```sh
buildscript {
 .....

    repositories {
.....
    }

    dependencies {
    ...
  classpath "com.squareup.okhttp3:okhttp:3.11.0"
.....
    }
}
```




```sh
import okhttp3.OkHttpClient
 OkHttpClient client = new  OkHttpClient()
```

i get can not resolve OkHttpClient !!??

i try other  :  https://blog.csdn.net/angcyo/article/details/88692186

```sh
import okhttp3.OkHttpClient
def client = new okhttp3.OkHttpClient()  
```
still  can not resolve !!

modify 

```sh
import okhttp3.OkHttpClient
def client =    OkHttpClient()  
```

it pass !!??

2. step2 

i close project  and re-open 

my gradle  fail !!!  AS (Android Studio ) can not show all struct ??!

3.  step3 

i git revert &  clean project   

```sh
import okhttp3.OkHttpClient
def client = new okhttp3.OkHttpClient()  
```
now  it pass

i try  add

```sh
task _okHttp3() {
    doFirst {

        URL url = new URL('https://tw.yahoo.com') 
        OkHttpClient client = new  OkHttpClient()
       Request request = new  Request().Builder() .url(url) .build()
       Response response = client.newCall(request).execute()
        println "Show "+response.body().string()
       response.close()
      }
}
```

i get 

```sh
* What went wrong:
Execution failed for task ':app:_okHttp3'.
> java.lang.NullPointerException (no error message)
```

**Comment by CMingTseng** [comment]
Dear Sir

i try to find What is wrong ?

```sh
def builder = new okhttp3.Request().Builder()
```

i get  error !!??

```sh
* What went wrong:
Execution failed for task ':app:_okHttp3'.
> java.lang.NullPointerException (no error message)
```

so 

new okhttp3.Request() is  null ?

i use


Android Studio   4.0.1 (Android Builder tool gradle is 4.0.1 )

maybe  something change ?

THX

**Comment by longforus** [comment]
![TIM截图20200921151638](https://user-images.githubusercontent.com/18444240/93740638-7ecf7e00-fc1d-11ea-8f0b-97273d0978ad.png)

change code like above,can be work.
but  ide can not resolve all reference,It always has been.
you can write code in a .java file, copy it in to gradle code file, it can be work,but less groovy benefits.
or useing .kts file write kotlin Code .that is very fun

**Comment by CMingTseng** [comment]
> .kts file

Dear Sir

how to  ref  .kts file ?

have demo  ? or  Ref ?

i  mail my wechat qrcode to your outlook.com  mail 

THX
